server:
  port: 8081



spring:
  datasource:
    jdbcUrl:
    user:
    password:
    driverClass: com.mysql.jdbc.Driver

  dlasource:
    jdbcUrl:
    user:
    password:
    driverClass: com.mysql.jdbc.Driver



mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml


ots:
  endpoint:
  accessId: 
  accessKey: 
  instanceName:
